name: Build sample Java Maven project
 
on: [push, pull_request]
 
jobs:
 
  build:
    runs-on: ubuntu-latest
    name: Build the Maven Project
    steps:
    - uses: actions/checkout@v2
   
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with: 
          java-version: '11'
    - name: Build and test project
      working-directory: github-actions-java-maven
      run: mvn -B package --file pom.xml
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact.jar
        path: github-actions-java-maven/target/github-actions-java-maven.jar
